// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.opendash.opendash_dash_engine

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is DashPigeonError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class DashPigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Where the K1G session is, mirroring the native `DashState`. */
enum class DashStage(val raw: Int) {
  IDLE(0),
  CONNECTING(1),
  AUTHENTICATING(2),
  READY(3),
  STREAMING(4),
  ERROR(5);

  companion object {
    fun ofRaw(raw: Int): DashStage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** What the platform last said about the Wi-Fi link, mirroring `WifiConnStatus`. */
enum class WifiStatus(val raw: Int) {
  IDLE(0),
  REQUESTING(1),
  CONNECTED(2),
  ERROR(3);

  companion object {
    fun ofRaw(raw: Int): WifiStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * `DebugLog`'s four levels. `debug` lines are per-packet hex dumps, which is why
 * the app routes them to `verbose` rather than to its own debug level.
 */
enum class DashLogLevel(val raw: Int) {
  DEBUG(0),
  INFO(1),
  WARNING(2),
  ERROR(3);

  companion object {
    fun ofRaw(raw: Int): DashLogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * One position on the route line sent to the dash.
 *
 * A class rather than the `List<List<double>>` this used to be: a pair of bare
 * lists has no way to say which element is the latitude, and the two are
 * interchangeable to the compiler right up to the point where the route draws
 * itself across the Indian Ocean.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NavPoint (
  val lat: Double,
  val lng: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NavPoint {
      val lat = pigeonVar_list[0] as Double
      val lng = pigeonVar_list[1] as Double
      return NavPoint(lat, lng)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lat,
      lng,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NavPoint
    return MessagesPigeonUtils.deepEquals(this.lat, other.lat) && MessagesPigeonUtils.deepEquals(this.lng, other.lng)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lat)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lng)
    return result
  }
  override fun toString(): String {
    return "NavPoint(lat=$lat, lng=$lng)"
  }
}

/**
 * Everything the engine publishes about itself, once per update.
 *
 * Replaces the 25-key map. The non-null fields carry the defaults the app's
 * hand-written `fromMap` used to apply — `followMode` and `headingUp` true,
 * the flags false — so that a value's absence and its default are one decision
 * made here, not two made independently on each side.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DashEngineState (
  val stage: DashStage,
  /**
   * True only on the single update from inside the native `disconnect()`.
   * Distinguishes "the rider asked" from "the session died", which otherwise
   * both arrive as [DashStage.idle].
   */
  val explicitDisconnect: Boolean,
  val wifiStatus: WifiStatus,
  val wifiSsid: String? = null,
  val wifiError: String? = null,
  /**
   * A destination has actually been sent to the dash, not merely previewed.
   * The dash draws a map either way; this drives the chrome. See spec/fsm.md.
   */
  val navigating: Boolean,
  val hasGps: Boolean,
  val riderLat: Double? = null,
  val riderLng: Double? = null,
  val riderBearing: Double? = null,
  /**
   * Ground speed straight from the fix, m/s, null without one. `NavEngine`
   * falls back to a flat 11 m/s for every ETA when this is missing.
   */
  val riderSpeed: Double? = null,
  val remainingKm: Double? = null,
  val offRoute: Boolean,
  val gpsLost: Boolean,
  val gpsWeak: Boolean,
  val errorMessage: String? = null,
  val followMode: Boolean,
  val headingUp: Boolean,
  /** A MapLibre camera zoom (13.50), not the hundredths the engine steps it in. */
  val zoom: Double,
  val nowPlayingTitle: String? = null,
  /** Only ever a RINGING call, unlike [hasActiveCall]. */
  val incomingCaller: String? = null,
  /**
   * Any call at all — ringing, answered or outgoing — so the dash's reject
   * button can end one that has already been answered.
   */
  val hasActiveCall: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DashEngineState {
      val stage = pigeonVar_list[0] as DashStage
      val explicitDisconnect = pigeonVar_list[1] as Boolean
      val wifiStatus = pigeonVar_list[2] as WifiStatus
      val wifiSsid = pigeonVar_list[3] as String?
      val wifiError = pigeonVar_list[4] as String?
      val navigating = pigeonVar_list[5] as Boolean
      val hasGps = pigeonVar_list[6] as Boolean
      val riderLat = pigeonVar_list[7] as Double?
      val riderLng = pigeonVar_list[8] as Double?
      val riderBearing = pigeonVar_list[9] as Double?
      val riderSpeed = pigeonVar_list[10] as Double?
      val remainingKm = pigeonVar_list[11] as Double?
      val offRoute = pigeonVar_list[12] as Boolean
      val gpsLost = pigeonVar_list[13] as Boolean
      val gpsWeak = pigeonVar_list[14] as Boolean
      val errorMessage = pigeonVar_list[15] as String?
      val followMode = pigeonVar_list[16] as Boolean
      val headingUp = pigeonVar_list[17] as Boolean
      val zoom = pigeonVar_list[18] as Double
      val nowPlayingTitle = pigeonVar_list[19] as String?
      val incomingCaller = pigeonVar_list[20] as String?
      val hasActiveCall = pigeonVar_list[21] as Boolean
      return DashEngineState(stage, explicitDisconnect, wifiStatus, wifiSsid, wifiError, navigating, hasGps, riderLat, riderLng, riderBearing, riderSpeed, remainingKm, offRoute, gpsLost, gpsWeak, errorMessage, followMode, headingUp, zoom, nowPlayingTitle, incomingCaller, hasActiveCall)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      stage,
      explicitDisconnect,
      wifiStatus,
      wifiSsid,
      wifiError,
      navigating,
      hasGps,
      riderLat,
      riderLng,
      riderBearing,
      riderSpeed,
      remainingKm,
      offRoute,
      gpsLost,
      gpsWeak,
      errorMessage,
      followMode,
      headingUp,
      zoom,
      nowPlayingTitle,
      incomingCaller,
      hasActiveCall,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DashEngineState
    return MessagesPigeonUtils.deepEquals(this.stage, other.stage) && MessagesPigeonUtils.deepEquals(this.explicitDisconnect, other.explicitDisconnect) && MessagesPigeonUtils.deepEquals(this.wifiStatus, other.wifiStatus) && MessagesPigeonUtils.deepEquals(this.wifiSsid, other.wifiSsid) && MessagesPigeonUtils.deepEquals(this.wifiError, other.wifiError) && MessagesPigeonUtils.deepEquals(this.navigating, other.navigating) && MessagesPigeonUtils.deepEquals(this.hasGps, other.hasGps) && MessagesPigeonUtils.deepEquals(this.riderLat, other.riderLat) && MessagesPigeonUtils.deepEquals(this.riderLng, other.riderLng) && MessagesPigeonUtils.deepEquals(this.riderBearing, other.riderBearing) && MessagesPigeonUtils.deepEquals(this.riderSpeed, other.riderSpeed) && MessagesPigeonUtils.deepEquals(this.remainingKm, other.remainingKm) && MessagesPigeonUtils.deepEquals(this.offRoute, other.offRoute) && MessagesPigeonUtils.deepEquals(this.gpsLost, other.gpsLost) && MessagesPigeonUtils.deepEquals(this.gpsWeak, other.gpsWeak) && MessagesPigeonUtils.deepEquals(this.errorMessage, other.errorMessage) && MessagesPigeonUtils.deepEquals(this.followMode, other.followMode) && MessagesPigeonUtils.deepEquals(this.headingUp, other.headingUp) && MessagesPigeonUtils.deepEquals(this.zoom, other.zoom) && MessagesPigeonUtils.deepEquals(this.nowPlayingTitle, other.nowPlayingTitle) && MessagesPigeonUtils.deepEquals(this.incomingCaller, other.incomingCaller) && MessagesPigeonUtils.deepEquals(this.hasActiveCall, other.hasActiveCall)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.explicitDisconnect)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.wifiStatus)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.wifiSsid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.wifiError)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.navigating)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasGps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.riderLat)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.riderLng)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.riderBearing)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.riderSpeed)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.remainingKm)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.offRoute)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gpsLost)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gpsWeak)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorMessage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.followMode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.headingUp)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.zoom)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nowPlayingTitle)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.incomingCaller)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasActiveCall)
    return result
  }
  override fun toString(): String {
    return "DashEngineState(stage=$stage, explicitDisconnect=$explicitDisconnect, wifiStatus=$wifiStatus, wifiSsid=$wifiSsid, wifiError=$wifiError, navigating=$navigating, hasGps=$hasGps, riderLat=$riderLat, riderLng=$riderLng, riderBearing=$riderBearing, riderSpeed=$riderSpeed, remainingKm=$remainingKm, offRoute=$offRoute, gpsLost=$gpsLost, gpsWeak=$gpsWeak, errorMessage=$errorMessage, followMode=$followMode, headingUp=$headingUp, zoom=$zoom, nowPlayingTitle=$nowPlayingTitle, incomingCaller=$incomingCaller, hasActiveCall=$hasActiveCall)"
  }
}

/**
 * A press on the dash's own joystick.
 *
 * Its own event, not a field of [DashEngineState]. On the map-backed channel the
 * two shared one stream and were told apart by asking whether the map happened to
 * contain a `button` key, which meant every reader of the state had to know about
 * buttons in order to ignore them — and a reader that forgot, like `NavLoop`,
 * silently processed a button event as a state update in which every field was null.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DashButtonEvent (
  val code: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DashButtonEvent {
      val code = pigeonVar_list[0] as Long
      return DashButtonEvent(code)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DashButtonEvent
    return MessagesPigeonUtils.deepEquals(this.code, other.code)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.code)
    return result
  }
  override fun toString(): String {
    return "DashButtonEvent(code=$code)"
  }
}

/**
 * One line of the native log, mirrored for the app's own logger.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DashLogEntry (
  val tag: String,
  val level: DashLogLevel,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DashLogEntry {
      val tag = pigeonVar_list[0] as String
      val level = pigeonVar_list[1] as DashLogLevel
      val message = pigeonVar_list[2] as String
      return DashLogEntry(tag, level, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      tag,
      level,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DashLogEntry
    return MessagesPigeonUtils.deepEquals(this.tag, other.tag) && MessagesPigeonUtils.deepEquals(this.level, other.level) && MessagesPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tag)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.level)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "DashLogEntry(tag=$tag, level=$level, message=$message)"
  }
}

/**
 * The saved dash Wi-Fi configuration, as the settings screen reads it.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DashConfigView (
  val ssidPrefix: String,
  val ssid: String,
  val password: String,
  /** No specific dash identified yet, so the next connect discovers by prefix. */
  val needsDiscovery: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DashConfigView {
      val ssidPrefix = pigeonVar_list[0] as String
      val ssid = pigeonVar_list[1] as String
      val password = pigeonVar_list[2] as String
      val needsDiscovery = pigeonVar_list[3] as Boolean
      return DashConfigView(ssidPrefix, ssid, password, needsDiscovery)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ssidPrefix,
      ssid,
      password,
      needsDiscovery,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DashConfigView
    return MessagesPigeonUtils.deepEquals(this.ssidPrefix, other.ssidPrefix) && MessagesPigeonUtils.deepEquals(this.ssid, other.ssid) && MessagesPigeonUtils.deepEquals(this.password, other.password) && MessagesPigeonUtils.deepEquals(this.needsDiscovery, other.needsDiscovery)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ssidPrefix)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ssid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.password)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.needsDiscovery)
    return result
  }
  override fun toString(): String {
    return "DashConfigView(ssidPrefix=$ssidPrefix, ssid=$ssid, password=$password, needsDiscovery=$needsDiscovery)"
  }
}

/**
 * Whether the system will let the app keep working with the screen off.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BatteryOptimisationStatus (
  /** Already exempt. */
  val ignoring: Boolean,
  /** A system prompt exists to open. */
  val canAsk: Boolean,
  /**
   * The exemption is necessary but not sufficient on this phone — see
   * `BatteryOptimisation`.
   */
  val emuiWorkaroundNeeded: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatteryOptimisationStatus {
      val ignoring = pigeonVar_list[0] as Boolean
      val canAsk = pigeonVar_list[1] as Boolean
      val emuiWorkaroundNeeded = pigeonVar_list[2] as Boolean
      return BatteryOptimisationStatus(ignoring, canAsk, emuiWorkaroundNeeded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ignoring,
      canAsk,
      emuiWorkaroundNeeded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BatteryOptimisationStatus
    return MessagesPigeonUtils.deepEquals(this.ignoring, other.ignoring) && MessagesPigeonUtils.deepEquals(this.canAsk, other.canAsk) && MessagesPigeonUtils.deepEquals(this.emuiWorkaroundNeeded, other.emuiWorkaroundNeeded)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ignoring)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.canAsk)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.emuiWorkaroundNeeded)
    return result
  }
  override fun toString(): String {
    return "BatteryOptimisationStatus(ignoring=$ignoring, canAsk=$canAsk, emuiWorkaroundNeeded=$emuiWorkaroundNeeded)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DashStage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WifiStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DashLogLevel.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NavPoint.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DashEngineState.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DashButtonEvent.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DashLogEntry.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DashConfigView.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatteryOptimisationStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DashStage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is WifiStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is DashLogLevel -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is NavPoint -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is DashEngineState -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is DashButtonEvent -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is DashLogEntry -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is DashConfigView -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BatteryOptimisationStatus -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DashEngineApi {
  fun getPlatformVersion(): String?
  fun connect()
  /**
   * Asynchronous because the farewell packets have to actually leave before the
   * socket closes, and the rider's "Отключить" button waits for it — see
   * `DashEngineController.disconnect`. Every path must answer: an unanswered
   * call leaves the future pending for the life of the process, i.e. a button
   * that spins forever.
   */
  suspend fun disconnect()
  fun setDestination(name: String?, lat: Double?, lng: Double?)
  fun clearDestination()
  /**
   * [jamSegments] is one traffic-level code per geometry segment, so it has
   * `points.length - 1` entries and index `i` covers `points[i]` to
   * `points[i + 1]` — the same convention as `nav.Route.jamSegments` on the app
   * side. Ignored, with a solid line drawn instead, if the length disagrees.
   */
  fun setNavState(remainingMeters: Double?, nextTurnMeters: Double?, maneuver: Long, etaHHMM: String?, offRoute: Boolean, points: List<NavPoint>, jamSegments: List<Long>)
  fun setFollowMode(enabled: Boolean)
  fun panBy(dx: Double, dy: Double)
  fun zoomIn()
  fun zoomOut()
  fun toggleHeadingUp()
  fun recenter()
  fun forgetDash()
  fun setSsid(ssid: String)
  fun setWifiPassword(password: String)
  fun getConfig(): DashConfigView
  fun batteryOptimisationStatus(): BatteryOptimisationStatus
  /** Shows the system prompt. False when there was nothing to ask. */
  fun requestIgnoreBatteryOptimisations(): Boolean
  /**
   * One Flutter-side error into the ride file. Rate-limited in Dart, at the
   * source — see `lib/util/error_reporting.dart`.
   */
  fun rideError(message: String)
  fun updateNowPlaying(title: String?, album: String, artist: String)
  fun updateCall(caller: String?)
  /** Turn-guidance chime. No Dart equivalent to `ToneGenerator`, so it lives here. */
  fun playChime()
  fun answerCall(): Boolean
  fun hangupCall(): Boolean
  fun skipNext(): Boolean
  fun skipPrevious(): Boolean
  fun isNotificationAccessGranted(): Boolean
  fun openNotificationAccessSettings()

  companion object {
    /** The codec used by DashEngineApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `DashEngineApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DashEngineApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.getPlatformVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPlatformVersion())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.connect()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.disconnect()
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setDestination$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String?
            val latArg = args[1] as Double?
            val lngArg = args[2] as Double?
            val wrapped: List<Any?> = try {
              api.setDestination(nameArg, latArg, lngArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.clearDestination$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearDestination()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setNavState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remainingMetersArg = args[0] as Double?
            val nextTurnMetersArg = args[1] as Double?
            val maneuverArg = args[2] as Long
            val etaHHMMArg = args[3] as String?
            val offRouteArg = args[4] as Boolean
            val pointsArg = args[5] as List<NavPoint>
            val jamSegmentsArg = args[6] as List<Long>
            val wrapped: List<Any?> = try {
              api.setNavState(remainingMetersArg, nextTurnMetersArg, maneuverArg, etaHHMMArg, offRouteArg, pointsArg, jamSegmentsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setFollowMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setFollowMode(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.panBy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dxArg = args[0] as Double
            val dyArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.panBy(dxArg, dyArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.zoomIn$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.zoomIn()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.zoomOut$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.zoomOut()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.toggleHeadingUp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.toggleHeadingUp()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.recenter$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.recenter()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.forgetDash$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.forgetDash()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setSsid$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ssidArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setSsid(ssidArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setWifiPassword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val passwordArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setWifiPassword(passwordArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.getConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getConfig())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.batteryOptimisationStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.batteryOptimisationStatus())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.requestIgnoreBatteryOptimisations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.requestIgnoreBatteryOptimisations())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.rideError$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.rideError(messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.updateNowPlaying$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String?
            val albumArg = args[1] as String
            val artistArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.updateNowPlaying(titleArg, albumArg, artistArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.updateCall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val callerArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.updateCall(callerArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.playChime$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.playChime()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.answerCall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.answerCall())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.hangupCall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hangupCall())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.skipNext$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.skipNext())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.skipPrevious$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.skipPrevious())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.isNotificationAccessGranted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isNotificationAccessGranted())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.openNotificationAccessSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openNotificationAccessSettings()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/** Native → Dart, one channel per stream. */
abstract class StateStreamHandler : MessagesPigeonEventChannelWrapper<DashEngineState> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StateStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.opendash_dash_engine.DashEngineEvents.state"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<DashEngineState>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<DashEngineState>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class ButtonStreamHandler : MessagesPigeonEventChannelWrapper<DashButtonEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ButtonStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.opendash_dash_engine.DashEngineEvents.button"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<DashButtonEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<DashButtonEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class LogStreamHandler : MessagesPigeonEventChannelWrapper<DashLogEntry> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: LogStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.opendash_dash_engine.DashEngineEvents.log"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<DashLogEntry>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<DashLogEntry>) {}

override fun onCancel(p0: Any?) {}
}
      
