// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Where the K1G session is, mirroring the native `DashState`.
enum DashStage {
  idle,
  connecting,
  authenticating,
  ready,
  streaming,
  error;
}

/// What the platform last said about the Wi-Fi link, mirroring `WifiConnStatus`.
enum WifiStatus {
  idle,
  requesting,
  connected,
  error;
}

/// `DebugLog`'s four levels. `debug` lines are per-packet hex dumps, which is why
/// the app routes them to `verbose` rather than to its own debug level.
enum DashLogLevel {
  debug,
  info,
  warning,
  error;
}

/// One position on the route line sent to the dash.
///
/// A class rather than the `List<List<double>>` this used to be: a pair of bare
/// lists has no way to say which element is the latitude, and the two are
/// interchangeable to the compiler right up to the point where the route draws
/// itself across the Indian Ocean.
class NavPoint {
  NavPoint({
    required this.lat,
    required this.lng,
  });

  double lat;

  double lng;

  List<Object?> _toList() {
    return <Object?>[
      lat,
      lng,
    ];
  }

  Object encode() {
    return _toList();  }

  static NavPoint decode(Object result) {
    result as List<Object?>;
    return NavPoint(
      lat: result[0]! as double,
      lng: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NavPoint || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lat, other.lat) && _deepEquals(lng, other.lng);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NavPoint(lat: $lat, lng: $lng)';
  }
}

/// Everything the engine publishes about itself, once per update.
///
/// Replaces the 25-key map. The non-null fields carry the defaults the app's
/// hand-written `fromMap` used to apply — `followMode` and `headingUp` true,
/// the flags false — so that a value's absence and its default are one decision
/// made here, not two made independently on each side.
class DashEngineState {
  DashEngineState({
    required this.stage,
    required this.explicitDisconnect,
    required this.wifiStatus,
    this.wifiSsid,
    this.wifiError,
    required this.navigating,
    required this.hasGps,
    this.riderLat,
    this.riderLng,
    this.riderBearing,
    this.riderSpeed,
    this.remainingKm,
    required this.offRoute,
    required this.gpsLost,
    required this.gpsWeak,
    this.errorMessage,
    required this.followMode,
    required this.headingUp,
    required this.zoom,
    this.nowPlayingTitle,
    this.incomingCaller,
    required this.hasActiveCall,
  });

  DashStage stage;

  /// True only on the single update from inside the native `disconnect()`.
  /// Distinguishes "the rider asked" from "the session died", which otherwise
  /// both arrive as [DashStage.idle].
  bool explicitDisconnect;

  WifiStatus wifiStatus;

  String? wifiSsid;

  String? wifiError;

  /// A destination has actually been sent to the dash, not merely previewed.
  /// The dash draws a map either way; this drives the chrome. See spec/fsm.md.
  bool navigating;

  bool hasGps;

  double? riderLat;

  double? riderLng;

  double? riderBearing;

  /// Ground speed straight from the fix, m/s, null without one. `NavEngine`
  /// falls back to a flat 11 m/s for every ETA when this is missing.
  double? riderSpeed;

  double? remainingKm;

  bool offRoute;

  bool gpsLost;

  bool gpsWeak;

  String? errorMessage;

  bool followMode;

  bool headingUp;

  /// A MapLibre camera zoom (13.50), not the hundredths the engine steps it in.
  double zoom;

  String? nowPlayingTitle;

  /// Only ever a RINGING call, unlike [hasActiveCall].
  String? incomingCaller;

  /// Any call at all — ringing, answered or outgoing — so the dash's reject
  /// button can end one that has already been answered.
  bool hasActiveCall;

  List<Object?> _toList() {
    return <Object?>[
      stage,
      explicitDisconnect,
      wifiStatus,
      wifiSsid,
      wifiError,
      navigating,
      hasGps,
      riderLat,
      riderLng,
      riderBearing,
      riderSpeed,
      remainingKm,
      offRoute,
      gpsLost,
      gpsWeak,
      errorMessage,
      followMode,
      headingUp,
      zoom,
      nowPlayingTitle,
      incomingCaller,
      hasActiveCall,
    ];
  }

  Object encode() {
    return _toList();  }

  static DashEngineState decode(Object result) {
    result as List<Object?>;
    return DashEngineState(
      stage: result[0]! as DashStage,
      explicitDisconnect: result[1]! as bool,
      wifiStatus: result[2]! as WifiStatus,
      wifiSsid: result[3] as String?,
      wifiError: result[4] as String?,
      navigating: result[5]! as bool,
      hasGps: result[6]! as bool,
      riderLat: result[7] as double?,
      riderLng: result[8] as double?,
      riderBearing: result[9] as double?,
      riderSpeed: result[10] as double?,
      remainingKm: result[11] as double?,
      offRoute: result[12]! as bool,
      gpsLost: result[13]! as bool,
      gpsWeak: result[14]! as bool,
      errorMessage: result[15] as String?,
      followMode: result[16]! as bool,
      headingUp: result[17]! as bool,
      zoom: result[18]! as double,
      nowPlayingTitle: result[19] as String?,
      incomingCaller: result[20] as String?,
      hasActiveCall: result[21]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DashEngineState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(stage, other.stage) && _deepEquals(explicitDisconnect, other.explicitDisconnect) && _deepEquals(wifiStatus, other.wifiStatus) && _deepEquals(wifiSsid, other.wifiSsid) && _deepEquals(wifiError, other.wifiError) && _deepEquals(navigating, other.navigating) && _deepEquals(hasGps, other.hasGps) && _deepEquals(riderLat, other.riderLat) && _deepEquals(riderLng, other.riderLng) && _deepEquals(riderBearing, other.riderBearing) && _deepEquals(riderSpeed, other.riderSpeed) && _deepEquals(remainingKm, other.remainingKm) && _deepEquals(offRoute, other.offRoute) && _deepEquals(gpsLost, other.gpsLost) && _deepEquals(gpsWeak, other.gpsWeak) && _deepEquals(errorMessage, other.errorMessage) && _deepEquals(followMode, other.followMode) && _deepEquals(headingUp, other.headingUp) && _deepEquals(zoom, other.zoom) && _deepEquals(nowPlayingTitle, other.nowPlayingTitle) && _deepEquals(incomingCaller, other.incomingCaller) && _deepEquals(hasActiveCall, other.hasActiveCall);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DashEngineState(stage: $stage, explicitDisconnect: $explicitDisconnect, wifiStatus: $wifiStatus, wifiSsid: $wifiSsid, wifiError: $wifiError, navigating: $navigating, hasGps: $hasGps, riderLat: $riderLat, riderLng: $riderLng, riderBearing: $riderBearing, riderSpeed: $riderSpeed, remainingKm: $remainingKm, offRoute: $offRoute, gpsLost: $gpsLost, gpsWeak: $gpsWeak, errorMessage: $errorMessage, followMode: $followMode, headingUp: $headingUp, zoom: $zoom, nowPlayingTitle: $nowPlayingTitle, incomingCaller: $incomingCaller, hasActiveCall: $hasActiveCall)';
  }
}

/// A press on the dash's own joystick.
///
/// Its own event, not a field of [DashEngineState]. On the map-backed channel the
/// two shared one stream and were told apart by asking whether the map happened to
/// contain a `button` key, which meant every reader of the state had to know about
/// buttons in order to ignore them — and a reader that forgot, like `NavLoop`,
/// silently processed a button event as a state update in which every field was null.
class DashButtonEvent {
  DashButtonEvent({
    required this.code,
  });

  int code;

  List<Object?> _toList() {
    return <Object?>[
      code,
    ];
  }

  Object encode() {
    return _toList();  }

  static DashButtonEvent decode(Object result) {
    result as List<Object?>;
    return DashButtonEvent(
      code: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DashButtonEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DashButtonEvent(code: $code)';
  }
}

/// One line of the native log, mirrored for the app's own logger.
class DashLogEntry {
  DashLogEntry({
    required this.tag,
    required this.level,
    required this.message,
  });

  String tag;

  DashLogLevel level;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      tag,
      level,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static DashLogEntry decode(Object result) {
    result as List<Object?>;
    return DashLogEntry(
      tag: result[0]! as String,
      level: result[1]! as DashLogLevel,
      message: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DashLogEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(tag, other.tag) && _deepEquals(level, other.level) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DashLogEntry(tag: $tag, level: $level, message: $message)';
  }
}

/// The saved dash Wi-Fi configuration, as the settings screen reads it.
class DashConfigView {
  DashConfigView({
    required this.ssidPrefix,
    required this.ssid,
    required this.password,
    required this.needsDiscovery,
  });

  String ssidPrefix;

  String ssid;

  String password;

  /// No specific dash identified yet, so the next connect discovers by prefix.
  bool needsDiscovery;

  List<Object?> _toList() {
    return <Object?>[
      ssidPrefix,
      ssid,
      password,
      needsDiscovery,
    ];
  }

  Object encode() {
    return _toList();  }

  static DashConfigView decode(Object result) {
    result as List<Object?>;
    return DashConfigView(
      ssidPrefix: result[0]! as String,
      ssid: result[1]! as String,
      password: result[2]! as String,
      needsDiscovery: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DashConfigView || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ssidPrefix, other.ssidPrefix) && _deepEquals(ssid, other.ssid) && _deepEquals(password, other.password) && _deepEquals(needsDiscovery, other.needsDiscovery);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DashConfigView(ssidPrefix: $ssidPrefix, ssid: $ssid, password: $password, needsDiscovery: $needsDiscovery)';
  }
}

/// Whether the system will let the app keep working with the screen off.
class BatteryOptimisationStatus {
  BatteryOptimisationStatus({
    required this.ignoring,
    required this.canAsk,
    required this.emuiWorkaroundNeeded,
  });

  /// Already exempt.
  bool ignoring;

  /// A system prompt exists to open.
  bool canAsk;

  /// The exemption is necessary but not sufficient on this phone — see
  /// `BatteryOptimisation`.
  bool emuiWorkaroundNeeded;

  List<Object?> _toList() {
    return <Object?>[
      ignoring,
      canAsk,
      emuiWorkaroundNeeded,
    ];
  }

  Object encode() {
    return _toList();  }

  static BatteryOptimisationStatus decode(Object result) {
    result as List<Object?>;
    return BatteryOptimisationStatus(
      ignoring: result[0]! as bool,
      canAsk: result[1]! as bool,
      emuiWorkaroundNeeded: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BatteryOptimisationStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ignoring, other.ignoring) && _deepEquals(canAsk, other.canAsk) && _deepEquals(emuiWorkaroundNeeded, other.emuiWorkaroundNeeded);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BatteryOptimisationStatus(ignoring: $ignoring, canAsk: $canAsk, emuiWorkaroundNeeded: $emuiWorkaroundNeeded)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DashStage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is WifiStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is DashLogLevel) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is NavPoint) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is DashEngineState) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is DashButtonEvent) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is DashLogEntry) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is DashConfigView) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is BatteryOptimisationStatus) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : DashStage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : WifiStatus.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : DashLogLevel.values[value];
      case 132:
        return NavPoint.decode(readValue(buffer)!);
      case 133:
        return DashEngineState.decode(readValue(buffer)!);
      case 134:
        return DashButtonEvent.decode(readValue(buffer)!);
      case 135:
        return DashLogEntry.decode(readValue(buffer)!);
      case 136:
        return DashConfigView.decode(readValue(buffer)!);
      case 137:
        return BatteryOptimisationStatus.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class DashEngineApi {
  /// Constructor for [DashEngineApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DashEngineApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<String?> getPlatformVersion() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.getPlatformVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<void> connect() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Asynchronous because the farewell packets have to actually leave before the
  /// socket closes, and the rider's "Отключить" button waits for it — see
  /// `DashEngineController.disconnect`. Every path must answer: an unanswered
  /// call leaves the future pending for the life of the process, i.e. a button
  /// that spins forever.
  Future<void> disconnect() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setDestination(String? name, double? lat, double? lng) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setDestination$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[name, lat, lng]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> clearDestination() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.clearDestination$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// [jamSegments] is one traffic-level code per geometry segment, so it has
  /// `points.length - 1` entries and index `i` covers `points[i]` to
  /// `points[i + 1]` — the same convention as `nav.Route.jamSegments` on the app
  /// side. Ignored, with a solid line drawn instead, if the length disagrees.
  Future<void> setNavState(double? remainingMeters, double? nextTurnMeters, int maneuver, String? etaHHMM, bool offRoute, List<NavPoint> points, List<int> jamSegments) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setNavState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[remainingMeters, nextTurnMeters, maneuver, etaHHMM, offRoute, points, jamSegments]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setFollowMode(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setFollowMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> panBy(double dx, double dy) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.panBy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[dx, dy]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> zoomIn() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.zoomIn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> zoomOut() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.zoomOut$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> toggleHeadingUp() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.toggleHeadingUp$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> recenter() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.recenter$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> forgetDash() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.forgetDash$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setSsid(String ssid) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setSsid$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[ssid]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setWifiPassword(String password) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.setWifiPassword$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[password]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<DashConfigView> getConfig() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.getConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DashConfigView;
  }

  Future<BatteryOptimisationStatus> batteryOptimisationStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.batteryOptimisationStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BatteryOptimisationStatus;
  }

  /// Shows the system prompt. False when there was nothing to ask.
  Future<bool> requestIgnoreBatteryOptimisations() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.requestIgnoreBatteryOptimisations$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// One Flutter-side error into the ride file. Rate-limited in Dart, at the
  /// source — see `lib/util/error_reporting.dart`.
  Future<void> rideError(String message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.rideError$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> updateNowPlaying(String? title, String album, String artist) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.updateNowPlaying$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[title, album, artist]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> updateCall(String? caller) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.updateCall$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[caller]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Turn-guidance chime. No Dart equivalent to `ToneGenerator`, so it lives here.
  Future<void> playChime() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.playChime$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> answerCall() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.answerCall$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> hangupCall() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.hangupCall$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> skipNext() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.skipNext$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> skipPrevious() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.skipPrevious$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> isNotificationAccessGranted() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.isNotificationAccessGranted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> openNotificationAccessSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.opendash_dash_engine.DashEngineApi.openNotificationAccessSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Native → Dart, one channel per stream.
/// Returns a broadcast [Stream] of events from the `state` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<DashEngineState> state( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel stateChannel =
      EventChannel('dev.flutter.pigeon.opendash_dash_engine.DashEngineEvents.state$instanceName', pigeonMethodCodec);
  return stateChannel.receiveBroadcastStream().map((dynamic event) {
    return event as DashEngineState;
  });
}
    
/// Returns a broadcast [Stream] of events from the `button` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<DashButtonEvent> button( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel buttonChannel =
      EventChannel('dev.flutter.pigeon.opendash_dash_engine.DashEngineEvents.button$instanceName', pigeonMethodCodec);
  return buttonChannel.receiveBroadcastStream().map((dynamic event) {
    return event as DashButtonEvent;
  });
}
    
/// Returns a broadcast [Stream] of events from the `log` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<DashLogEntry> log( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel logChannel =
      EventChannel('dev.flutter.pigeon.opendash_dash_engine.DashEngineEvents.log$instanceName', pigeonMethodCodec);
  return logChannel.receiveBroadcastStream().map((dynamic event) {
    return event as DashLogEntry;
  });
}
    
